### ISSUE TITLE
"pnpx astro add" adds / to import statement, causing an error

### ISSUE THREAD

**Issue by lukeshafer** [tokencss/tokencss#11]
Just installed tokencss via `pnpx astro add @tokencss/astro` (excited to try it!) and encountered a (simple) error in `astro.config.mjs`, due to the integration sticking a / symbol at the end of the import name. 

```mjs
import { defineConfig } from 'astro/config';
import tokencss/ from "@tokencss/astro";

/* ... */

// https://astro.build/config
export default defineConfig({
  /* ... */
  integrations: [tokencss/()]
})
```

Easy enough to fix the config file but thought I'd submit an issue! I wasn't able to test if the behavior is different on an npm project. I also did not have this issue when adding other integrations to this project.

**Comment by natemoo-re** [comment]
Whoops! This is an Astro bug with scoped packages actually, if you could open an issue there that would be awesome.

**Comment by lukeshafer** [comment]
Awesome! Makes sense - and it looks like the fix has already been merged on Astro. I'll close this issue!
